# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spring 2016 Project
email: matt@badmatt.com
description: > # this means to ignore newlines until "baseurl:"
  Spring 2016 ISE Masters project
baseurl: "/2016spr/" # the subpath of your site, e.g. /blog
url: "http://badmatt.com" # the base hostname & protocol for your site
twitter_username: 
github_username: mjcollin

# Build settings
markdown: kramdown
